# Generated by Django 5.1.2 on 2024-10-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_disk",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Disk"
                    ),
                ),
                (
                    "free_disk",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Free Disk"
                    ),
                ),
                (
                    "used_disk",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Used Disk"
                    ),
                ),
            ],
            options={
                "verbose_name": "Disk",
                "verbose_name_plural": "Disks",
                "db_table": "disk",
                "ordering": ["id"],
            },
        ),
    ]
