# Generated by Django 5.1.2 on 2024-10-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="free_disk",
            field=models.IntegerField(verbose_name="Free Disk"),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="total_disk",
            field=models.IntegerField(verbose_name="Total Disk"),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="used_disk",
            field=models.IntegerField(verbose_name="Used Disk"),
        ),
    ]
