# Generated by Django 5.1.2 on 2024-10-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_monitor_free_disk_alter_monitor_total_disk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("core_0_usage", models.FloatField(verbose_name="Core 0 Usage (%)")),
                ("core_1_usage", models.FloatField(verbose_name="Core 1 Usage (%)")),
                ("core_2_usage", models.FloatField(verbose_name="Core 2 Usage (%)")),
                ("core_3_usage", models.FloatField(verbose_name="Core 3 Usage (%)")),
                (
                    "total_usage",
                    models.FloatField(
                        editable=False, verbose_name="Total CPU Usage (%)"
                    ),
                ),
            ],
            options={
                "verbose_name": "CPU",
                "verbose_name_plural": "CPUs",
                "db_table": "cpu",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_ram", models.IntegerField(verbose_name="Total RAM (GB)")),
                ("free_ram", models.IntegerField(verbose_name="Free RAM (GB)")),
                ("used_ram", models.IntegerField(verbose_name="Used RAM (GB)")),
            ],
            options={
                "verbose_name": "RAM",
                "verbose_name_plural": "RAMs",
                "db_table": "ram",
                "ordering": ["id"],
            },
        ),
        migrations.RenameModel(
            old_name="Monitor",
            new_name="Disk",
        ),
    ]
