# Generated by Django 5.1.2 on 2024-10-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_cpu_created_at_cpu_updated_at_disk_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disk",
            name="free_disk",
            field=models.FloatField(verbose_name="Free Disk"),
        ),
        migrations.AlterField(
            model_name="disk",
            name="total_disk",
            field=models.FloatField(verbose_name="Total Disk"),
        ),
        migrations.AlterField(
            model_name="disk",
            name="used_disk",
            field=models.FloatField(verbose_name="Used Disk"),
        ),
        migrations.AlterField(
            model_name="ram",
            name="free_ram",
            field=models.FloatField(verbose_name="Free RAM (GB)"),
        ),
        migrations.AlterField(
            model_name="ram",
            name="total_ram",
            field=models.FloatField(verbose_name="Total RAM (GB)"),
        ),
        migrations.AlterField(
            model_name="ram",
            name="used_ram",
            field=models.FloatField(verbose_name="Used RAM (GB)"),
        ),
    ]
