# Generated by Django 5.1.2 on 2024-10-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_disk_free_disk_alter_disk_total_disk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpu",
            name="core_0_usage",
        ),
        migrations.RemoveField(
            model_name="cpu",
            name="core_1_usage",
        ),
        migrations.RemoveField(
            model_name="cpu",
            name="core_2_usage",
        ),
        migrations.RemoveField(
            model_name="cpu",
            name="core_3_usage",
        ),
        migrations.AddField(
            model_name="cpu",
            name="cores",
            field=models.CharField(max_length=255, null=True, verbose_name="CPU Name"),
        ),
    ]
